apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-cluster
  namespace: es-namespace
spec:
  serviceName: es-svc
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
        ports:
        - containerPort: 9200
          name: api
          protocol: TCP
        - containerPort: 9300
          name: node
          protocol: TCP
        volumeMounts:
        - name: edata
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: clusterlogs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "node-cluster-0.es-svc,node-cluster-1.es-svc"
          - name: cluster.initial_master_nodes
            value: "node-cluster-0,node-cluster-1"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
      initContainers:
      - name: increase-vm
        image: alpine
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      
  volumeClaimTemplates:
  - metadata:
      name: edata
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: elastic-storage
      resources:
        requests:
          storage: 512Mi