kind: Service
apiVersion: v1
metadata:
  name: es-svc 
  namespace: es-namespace
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: api
    - port: 9300
      name: node