kind: Service
apiVersion: v1
metadata:
  name: es-svc1 
  namespace: es-namespace
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      nodePort: 31000
  type: NodePort